name: Pipeline CICD projet Master

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: masterapp
  REPO: ghcr.io

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lancer les tests
        run: ls -lah

  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t ${{env.IMAGE_NAME}} .

      - name: Run image
        run: docker run -d -p 3000:3000 ${{env.IMAGE_NAME}}

      - name: Tager en version courante
        run: "docker tag ${{env.IMAGE_NAME}} ${{env.REPO}}/thibaut-renaut/${{env.IMAGE_NAME}}:1.0"

      - name: Tager en version latest
        run: "docker tag ${{env.IMAGE_NAME}} ${{env.REPO}}/thibaut-renaut/${{env.IMAGE_NAME}}:latest"

      - name: connexion a GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REPO }}
          username: thibaut-renaut
          password: ${{ secrets.TOKENCICD }}

      - name: Push de l'image V1.0
        run: "docker push ${{env.REPO}}/thibaut-renaut/${{env.IMAGE_NAME}}:1.0"

      - name: Push de l'image latest
        run: "docker push ${{env.REPO}}/thibaut-renaut/${{env.IMAGE_NAME}}:latest"
